@echo off
start cmd /c "python main.py --logic Algorithm --email=test@email.com --name=stima --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test1@email.com --name=stima1 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test2@email.com --name=stima2 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test3@email.com --name=stima3 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test3@email.com --name=stima4 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test3@email.com --name=stima5 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test@email.com --name=stima6 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test1@email.com --name=stima7 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test2@email.com --name=stima8 --password=123456 --team etimo"
start cmd /c "python main.py --logic Algorithm --email=test3@email.com --name=stima9 --password=123456 --team etimo"